dir_list:
  home: "~/Health-Privacy-Challenge"
  meta: "data/meta"
  processed_data: "data/processed"
  data_save_dir: "data_splits"
  split_save_dir: "data_splits/split_indices"

dataset_config:
  name: "TCGA-BRCA" #"TCGA-COMBINED" # 
  count_file: "data/processed/TCGA-BRCA_primary_tumor_star_deseq_VST_lmgenes.tsv" #"TCGA-COMBINED" # 
  annot_file: "data/meta/TCGA-BRCA_primary_tumor_subtypes.csv" #"TCGA-COMBINED" # 
  sample_col_name: "samplesID" 
  subtype_col_name: "Subtype" #"cancer_type"  "Subtype"
  num_splits: 5
  random_seed: 42

generator_name: "pgg_pgm"
generate: True
train: True
load_from_checkpoint: False

pgg_pgm_config:
  epsilon: 50.0
  iterations: 10000

